name: Publish Python 🐍 distributions 📦 to PyPI

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Build and inspect Python 🐍 package 📦
        uses: hynek/build-and-inspect-python-package@14c7e53f5d033cfa99f7af916fa59a6f7f356394 # v2.11.0
        with:
          attest-build-provenance-github: ${{ github.event.action == 'published' }}

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs: build
    if: ${{ github.event.action == 'published' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/${{ github.repository }}/${{ github.ref_name }}
    permissions:
      id-token: write

    steps:
    - name: Download dists
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: Packages
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70 # v1.12.3
      with:
          attestations: true
          verbose: true
          print-hash: true
